# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb1baa5f2afed281d035617c467f1f8b8233e1a22c087066dd1ff6b8736151862ef42ddfd6b5d3b5547a634a06fc08f26f5f266899bf97c8fdb5eef029aa1ea9

test:
  secret_key_base: 6f126c9d9de4b8abf80e9df1aaf961cf03b9dfc1eafbb2ae8b2ebe4a755283b607ea73168671eaa82ed41abd13344a1c98934b458c7006563f063826f2cc5d2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
